
* Nome do Software (ou Biblioteca):
- SIMULADOR DE SOLUÇÕES ANALÍTICAS ADIMENSIONAIS DA
EQUAÇÃO DA DIFUSIVIDADE HIDRÁULICA PARA FLUXOS
LINEAR E RADIAL

* Resumo e/ou informação extra: 
- A partir da descoberta de uma acumulação de petróleo diversas informações podem
ser obtidas. Das mais importantes, pode-se citar como exemplo a quantidade de hidro-
carbonetos que se pode retirar dessa jazida e o tempo em que essa produção se efetuará.
Dentro da engenharia de petróleo, engenheiros de reservatório constantemente buscam
solucionar problemas envolvendo uxos monofásicos de uidos de baixa compressibilidade
que partem das as equações fundamentais da mecânica dos uidos que descrevem o trans-
porte de líquidos em meios porosos. A principal equação que rege esse estudo do uxo
em meios porosos é a Equação da Difusividade Hidráulica e ao resolver os problemas de
valor inicial e de contorno formados por essa equação, é possível obter os modelos físicos
de interesse que são encontrados no campo.
A necessidade de monitoramento do comportamento do reservatório é evidente e prever
como será o seu comportamento auxilia diretamente na tomada de decisões a respeito das
operações realizadas e serve de base para os testes de pressão que visam a obtenção de
vários parâmetros do reservatório (fator de película, volume poroso drenado, limites do
reservatório, etc).

* Versão: 
- 1.0.

* Data:
- 2013/2 - segundo semestre.
  
* Autor de Contato:
- André Duarte Bueno <andreduartebueno@gmail.com>

* Lista dos Autores:
- Letícia Fernandes Sakai
- Lucas Rodrigues Tavares
- André Duarte Bueno <andreduartebueno@gmail.com>

* Áreas de pesquisa vinculadas: 
- Modelagem Matemática Computacional
- Engenharia de Reservatório

* Vinculo com: 
- Trabalho da disciplina de programação prática.

* Paradigmas: 
- POO - Programação Orientada a Objeto (códigos em C++)

* Tipo de Interface: 
- Terminal e gráfica (gnuplot).

* Plataformas Suportadas: 
- Windows e GNU/Linux e Mac OS X (não testada).

* Linguagens Utilizadas: 
- C++ 11.

* Bibliotecas Utilizadas (dependências):
- CGnuplot - https://github.com/ldsc/CGnuplot

* Softwares utilizados (dependências)
- gnuplot http://www.gnuplot.info/

* Tipo de Licença:
- GPL
- Entre em contato com o Prof. André Duarte Bueno
  andreduartebueno@gmail.com
  para que o mesmo gere um novo projeto no github do ldsc para que você (e sua equipe) possam trabalhar na nova versão.
- Se este projeto tem como número de versão 1.0 a nova versão deverá ser 2.0 e assim sucessivamente.
- Os nomes dos autores originais deve ser preservada na nova versão, ou seja, adicione a informação do número da versão, os nomes dos membros da nova equipe, mas jamais apague os nomes dos autores originais (isto seria plágio).
- Na descrição do projeto informe que trata-se de uma nova versão, que tem como base a versão anterior e DESTAQUE COM CLAREZA E OBJETIVIDADE QUAIS AS NOVIDADES DA NOVA VERSÃO.
  
* Links:

